job offer website/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using WebApplication1.Models;

namespace job_offer_website.Models
{
    public class Job
    {
        public int Id { get; set; }
        [DisplayName("اسم الوظيفه")]
        public string JobTitle { get; set; }
        [DisplayName("وصف الوظيفه")]
        public string JobContent { get; set; }
        [DisplayName("صوره الوظيفه")]
        public string JobImage { get; set; }
        [DisplayName("نوع الوظيفه")]
        public int CategoryId { get; set; }
        public string UserId { get; set; }
        public virtual Category Category { get; set; }
        public virtual ApplicationUser User { get; set; }

    }
}

job offer website/Models/JobsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace job_offer_website.Models
{
    public class JobsViewModel
    {
        public string JobTitle { get; set; }
        public IEnumerable<ApplyForJob> Items { get; set; }
    }
}

job offer website/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using job_offer_website.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace job_offer_website.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }
      

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Job job,HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if(upload !=null)
                {
                    job.UserId = User.Identity.GetUserId();
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                }
               
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Job job,HttpPostedFileBase uploadimg)
        {
            if (ModelState.IsValid)
            {

                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);
                //if (System.IO.File.Exists(oldPath)==true)
                //{
                //    System.IO.File.Delete(oldPath);
                //}
                if (uploadimg != null)
                {

                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), uploadimg.FileName);
                    uploadimg.SaveAs(path);
                    job.JobImage = uploadimg.FileName;
                }
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

job offer website/Views/Jobs/Create.cshtml
@model job_offer_website.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>انشاء</h2>

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
  

    <div id="div-error" style="display:none" class="alert alert-danger">
        <span id="error-msg"></span>
    </div>
    <div class="form-horizontal">
        <h4>وظيفه</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="imgBtn" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="انشاء" class="btn btn-default" id="saveimg" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("العوده الي القائمه ", "Index")
</div>
<script src="~/scripts/jquery.js"></script>
<script>
    $(function () {
        if ($("#saveimg").click(function () {

            if ($("#imgBtn").val() == "") {

                $("#div-error").fadeIn();
                $("#error-msg").append("برجاء التأكد من ادخال الصوره ")
                return false;
            }

            if ($("#imgBtn").val() != "") {
                var imgName = $("#imgBtn").val();
                var imgEx = imgName.split('.');
                imgEx = imgEx[imgEx.length - 1];
                console.log(imgEx);

                var valitaionExt = ["jpg", "png", "bmp", "gif"];
                if ($.inArray(imgEx, valitaionExt) == -1) {
                    $("#div-error").fadeIn();
                    $("#error-msg").append("برجاء التأكدمن ان الصوره المدخله  .jpg  او png ")
                    return false;

                }

                // check if image size is valid(2 mg)
                var s = document.getElementById("saveimg").files[0].size / 1024 / 1024;
                console.log(s);
                if (s > 1) {
                    $("#div-error").fadeIn();
                    $("#error-msg").append("تأكد من حجم الصوره ")
                    return false;
                }


            }

        }));



    });
</script>

job offer website/Views/Jobs/Delete.cshtml
@model job_offer_website.Models.Job

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

job offer website/Views/Jobs/Details.cshtml
@model job_offer_website.Models.Job

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>تفاصيل</h2>

<div>
    <h4>الوظيفه</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
           <img src="~/Uploads/@Html.DisplayFor(model=>model.JobImage)" 
                class="thumbnail" 
                style="height:48px; width:48px" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("تعديل", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("العوده الي القائمه", "Index")
</p>

job offer website/Views/Jobs/Edit.cshtml
@model job_offer_website.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>تعديل</h2>

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>الوظيفه</h4>
    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="error-msg"></span>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.JobImage)

    <div class="form-group">
        @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="uploadimg" id="saveimg" />
            @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "نوع الوظيفه", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="حفظ" class="btn btn-default" id="save" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("العوده الي القائمه", "Index")
</div>
<script src="~/scripts/jquery.js"></script>
<script>
    $(function () {
        if ($("#save").click(function () {

            //if ($("#saveimg").val() == "") {

            //    $("#error-div").fadeIn();
            //    $("#error-msg").append("برجاء التأكد من ادخال الصوره ")
            //    return false;
            //}

            if ($("#saveimg").val() != "") {
                var imgName = $("#saveimg").val();
                var imgEx = imgName.split('.');
                imgEx = imgEx[imgEx.length - 1];
                console.log(imgEx);
               
                var valitaionExt = ["jpg", "png", "bmp", "gif"];
                if ($.inArray(imgEx, valitaionExt)==-1)
                {
                    $("#error-div").fadeIn();
                    $("#error-msg").append("برجاء التأكدمن ان الصوره المدخله  .jpg  او png ")
                    return false;
                  
                }

                // check if image size is valid(2 mg)
                var s = document.getElementById("saveimg").files[0].size / 1024 / 1024;
                console.log(s);
                if (s > 1) {
                    $("#error-div").fadeIn();
                    $("#error-msg").append("تأكد من حجم الصوره ")
                    return false;
                }
                

            }
           
        }));



    });
</script>

job offer website/Views/Jobs/Index.cshtml
@model IEnumerable<job_offer_website.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div style="margin-right:40px">
    <h2 >الوظيفه</h2>

    <p st>
        @Html.ActionLink("انشاء جديد", "Create")
    </p>
</div>
<table class="table table-stripped table-hover table-bordered" style="margin-right:40px">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobContent)
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(model=>item.JobImage)"
                 class="thumbnail"
                 style="height:48px; width:48px" />
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.Id }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.Id }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>